### PR TITLE
Feature/setup

### PR DESCRIPTION
**Pull request by oranj**
You should be able to modify the QUnit config if you see fit. This adds a `setup` callback to the grunt config.

Also, fixed some spelling

### CODE REVIEW

**Comment by cedmax** [comment]
I like the idea of enabling the user to configure QUnit, but wouldn't it be better to pass through a configuration object rather than a function? I feel it would be more consistent with the rest of  configuration options, what you think?

**Comment by oranj** [comment]
I agree with that, but because phantom is sandboxing everything, we have to run it through a function anyways. I'm pretty new with phantom, so I wasn't sure the best way to pass things in- a function seemed simplest.

**Comment by oranj** [comment]
I also like the idea of being able to run `QUnit.start()` right away, and not have to run that in my tests.

**Comment by cedmax** [comment]
The `Qunit.start()` can be avoided if you set the config.autostart to true, therefore a config object should be enough (and less dangerous in terms of screwing up with the phantom page context, which should be as clean as possible to maintain the test execution reliable).

We just need to extend the `Qunit.config` object with a `testOpt.qunit` one, passing it to the phantom page context in the same way I did with the `testOpt.require` (using `phantomHelper.evaluate`, as in the `initRequire` function) and I'd do it just after it sets the `QUnit.config` default values, so that we don't need to worry it to be executed more than once.

If you want to deal with these changes I'd be more than comfortable to let you handle it, if not I'll try to work on it later this week, but I can't promise anything yet.

**Comment by cedmax** [comment]
Hi there, sorry for the delay.
I created a branch here: https://github.com/cedmax/grunt-qunit-amd/tree/QUnitConfigurable

would you mind checking if it does fit your use case? 
As far as I can tell is perfectly backward compatible, I can't wait to promote it to master

**Comment by cedmax** [comment]
@oranj next week I'll test in deep and create a new release, I was wondering if you had any time to check the branch

**Comment by oranj** [comment]
I won't be back in town until early February, but I can look at it then.
Regarding QUnit.start(), does the autostart work while using AMD?

**Comment by cedmax** [comment]
to be honest I haven't thought about it, but now that you mentioned it that might be the reason why I disabled it in the first place: require is async, so no, it wouldn't, but anyway `Qunit.config.autostart = true` and `Qunit.start()` launched straight away do exactly the same thing as far as I know, therefore the configuration would be enough for that use case too.
I'll do my tests and then wait a feedback from you. 
Thanks

**Comment by cedmax** [comment]
I added the feature to master

**Pull request closed without merging**
